name: pipeline

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsm6 libxext6
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Prepare synthetic video (5s, 640x360, 30fps)
        run: |
          ffmpeg -f lavfi -i testsrc=size=640x360:rate=30 -t 5 -pix_fmt yuv420p 9.mp4 -y
      - name: Run full pipeline
        run: |
          python - << 'PY'
          import os
          from main_pipeline import SoccerHighlightPipeline
          p = SoccerHighlightPipeline()
          p.run_full_pipeline('9.mp4', target_player_id=1, output_dir='output')
          PY
      - name: Upload artifacts (outputs)
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: |
            output/*.json
            output/*.mp4
            output/*
